---
#-------------------------------
# General Site Settings

title: creamycode
logo:
author: themefisher
description: this is meta description
email: creamycode87@gmail.com
phone: +82 010 8764 8602
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  # - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: 풀스택 웹 개발자 입니다.

social:
  # - { icon: "ti-facebook", link: "#" }
  # - { icon: "ti-instagram", link: "#" }
  # - { icon: "ti-dribbble", link: "#" }
  # - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: 

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Language Section

#-------------------------------
# Skills Section Start

skills-main-title: 주요 기술
language-title: Language
language-skills:
  - { name: Typescript, color: "#fdb157", value: "90%" }
  - { name: Javascript, color: "#9473e6", value: "60%" }
  - { name: Python, color: "#bdecf6", value: "80%" }

frontend-title: Frontend
frontend-skills:
  - { name: Angular, color: "#fdb157", value: "90%" }
  - { name: Ngrx, color: "#9473e6", value: "60%" }
  - { name: Rxjs, color: "#bdecf6", value: "80%" }
  - { name: React, color: "#bdecf6", value: "80%" }
  - { name: CSS, color: "#bdecf6", value: "80%" }
  - { name: SCSS, color: "#bdecf6", value: "80%" }
  - { name: JQuery, color: "#bdecf6", value: "80%" }

backend-title: Backend
backend-skills:
  - { name: NodeJS, color: "#fdb157", value: "90%" }
  - { name: NestJS, color: "#9473e6", value: "60%" }
  - { name: Express, color: "#bdecf6", value: "80%" }

etc-title: ETC
etc-skills:
  - { name: Ansible, color: "#fdb157", value: "90%" }
  - { name: Docker, color: "#9473e6", value: "60%" }
  - { name: Gitlab CI/CD, color: "#bdecf6", value: "80%" }
  - { name: Electron, color: "#bdecf6", value: "80%" }

#-------------------------------
# Skills Section End

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Wins (2018.04 ~ ing)", type: "wins" }
  - { title: "Openit (2013.11 ~ 2018.01)", type: "openit" }
  - { title: "개인 프로젝트", type: "study" }

portfolio-items:
  - image: "assets/images/portfolio/sniper-rms-1.jpg"
    title: "SNIPER-RMS"
    range: "2019.01 ~ 현재"
    url: "sniper-rms.html"
    stack: ['Angular', 'Ngrx', 'NestJS', 'Mariadb', 'SocketIO', 'Jest', 'Cypress']
    portfolio-type:
      - type: "wins"
    summary: "
    - 현재 팀의 메인 시스템으로, 보안장비들의 정책관리 시스템이며, 주요기능으로 센서관리, 정책가져오기, 정책배포, 정책편집기능을 제공한다.<br>
    - i18n 일본어지원 <br>
    "

  - image: "assets/images/portfolio/devops-1.png"
    title: "Team Devops & CI/CD 구성"
    range: "2020.01 ~ 2021.12"
    url: "devops.html"
    stack: ['Docker', 'Portainer', 'Gitlab CI/CD', 'Ansible',  'python']
    portfolio-type:
      - type: "wins"
    summary: "
    - Docker 기반 개발환경 구성 및 Ansible을 통한 업무 자동화<br>
    - Gitlab CI/CD 및 Ansible을 통해 제품 test(lint, unit, e2e), packaging, deploy 과정 자동화<br>
    "

  - image: "assets/images/portfolio/ansible-1.png"
    title: "AnsibleModule 개발"
    range: "2019.07 ~ 2020.06"
    url: "devops.html"
    stack: ['Ansible',  'python']
    portfolio-type:
      - type: "wins"
    summary: "
    - 보안장비의 기능별 Ansible 모듈 개발<br>
    - Playbook 기반 모듈 테스트케이스 개발
    "

  - image: "assets/images/portfolio/tango1.jpg"
    title: "SKT TANGO DW 운영"
    range: "2017.01 ~ 2018.01"
    url: "tango.html"
    stack: ['Hadoop', 'Spark', 'Grafana', 'Python']
    portfolio-type:
      - type: "openit"
    summary: "
    &nbsp;SKT의 여러 Legacy System Data를 수집(일평균 4TB)하여 ODS, DW, DM 각각의 단계별 데이터로 가공하고 관리하는 DW 운영 및 해당 데이터를 조회할 수 있는 WorkBench WAS 운영
    "

  - image: "assets/images/portfolio/openclib2.jpg"
    title: "Openclib 개발"
    range: "2016.01 ~ 2016.09"
    url: "openclib.html"
    stack: ['NodeJS', 'AngularJS', 'Electron', 'Express', 'jquery', 'bootstrap', 'mysql', 'SocketIO']
    portfolio-type:
      - type: "openit"
    summary: "
    - OpenTok 그룹웨어 고도화 프로젝트<br>
    - 제품 기획부터 개발까지 모두 참여
    "

  - image: "assets/images/portfolio/opentok1.png"
    title: "오픈톡 그룹웨어 개발 및 유지보수"
    range: "2014.01 ~ 2016.04"
    url: "opentok.html"
    stack: ['spring', 'jsp', 'jquery', 'bootstrap', 'mysql', 'SocketIO']
    portfolio-type:
      - type: "openit"
    summary: "
    - 주요기능 개발<br>
    - GS 인증 대응<br>
    - 고객사 그룹웨어 구축
    "

#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"

#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

# contact-title: Contact Info
# contact-email: steve.fruits@email.com
